name: Deploy – Static Site (FTPS)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      - ".github/**"
  workflow_dispatch:

concurrency:
  group: deploy-static-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via FTPS to netcup
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 91.204.46.169            # ✅ same as in Cyberduck
          port: 21                         # ✅ same
          protocol: ftps                   # ✅ same ("FTP-SSL (Explicit AUTH TLS)")
          username: ${{ secrets.NC_FTP_USER }}
          password: ${{ secrets.NC_FTP_PASS }}
          local-dir: ./public/             # ✅ must end with /
          server-dir: /coocooschka.de/httpdocs/  # ✅ same as your Cyberduck path
          timeout: 300000
          log-level: verbose
          exclude: |
            **/.git*
            **/.github/**
            **/.DS_Store
            **/node_modules/**
            **/README.md